"""
Parse the Tally corpus through the real connector and emit canonical JSON.

The bridge between a Python ingestion layer and a TypeScript seed. Deliberately
thin: it does no transformation of its own beyond serialising what
`TallyConnector` produced, so that what the seed loads is exactly what the
parser understood — not a second interpretation of the same XML.

That matters more than it sounds. If this script "helpfully" cleaned up dates or
recomputed amounts, the corpus in the database would no longer be evidence that
the ingestion path works; it would be evidence that this script works.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from datetime import date
from decimal import Decimal

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "backend"))

from app.connectors.tally.connector import TallyConnector, TallyConfig  # noqa: E402


class FileTransport:
    """
    Serves the generated files where the connector expects Tally's HTTP endpoint.

    Routing on the request body rather than taking an explicit argument keeps the
    connector's own request-building code in the path — it is the connector that
    decides what to ask for, exactly as it would against a live Tally.
    """

    def __init__(self, directory: pathlib.Path) -> None:
        self.directory = directory

    def send(self, payload: str) -> str:
        p = payload.lower()
        if "bills" in p or "billdate" in p:
            return (self.directory / "invoices.xml").read_text()
        if "receipt" in p or "voucher" in p:
            return (self.directory / "payments.xml").read_text()
        return (self.directory / "customers.xml").read_text()


def encode(value):
    if isinstance(value, Decimal):
        # As a string. Through float it would pick up exactly the representation
        # error the whole money layer exists to avoid, at the last possible step.
        return str(value)
    if isinstance(value, date):
        return value.isoformat()
    raise TypeError(f"unencodable: {type(value)}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--corpus", type=pathlib.Path, default=pathlib.Path("data/corpus"))
    ap.add_argument("--out", type=pathlib.Path, default=pathlib.Path("data/corpus/canonical.json"))
    args = ap.parse_args()

    connector = TallyConnector(
        TallyConfig(company="Synthetic Corpus"),
        transport=FileTransport(args.corpus),
    )

    invoices = connector.get_invoices("corpus")
    customers = connector.get_customers("corpus")

    payload = {
        "source": "synthetic — generated by scripts/corpus/generate_tally.py",
        "parsedBy": "backend/app/connectors/tally/TallyConnector",
        "invoices": [i.model_dump() for i in invoices],
        "customers": [c.model_dump() for c in customers],
    }

    args.out.write_text(json.dumps(payload, default=encode, indent=1))

    unpaid = [i for i in invoices if i.payment_status != "PAID"]
    print(f"parsed {len(invoices)} invoices, {len(customers)} customers")
    print(f"  {len(unpaid)} still outstanding — these are what there is to finance")
    print(f"  wrote {args.out}")


if __name__ == "__main__":
    main()
