/**
 * GET/PATCH /api/providers/:id/mandate — a provider's own underwriting terms.
 *
 * The lender dashboard's forms previously held these in `useState` and saved
 * them nowhere, so a lender could set a hurdle rate and a concentration cap and
 * neither reached the record the market actually prices against (#46).
 *
 * **Tenancy matters here more than on any other route.** A provider's mandate
 * is private by construction (`01-commerce-analysis.md` §6): cost of funds and
 * hurdle rate are exactly what a competitor would want, and the scoring engine
 * must not read them either, or bids would be generated by the logic that ranks
 * them. `GET /api/providers` deliberately omits these fields; this route serves
 * them only for the provider's own id, which is why it is a separate endpoint
 * rather than a flag on the list.
 */

import { prisma } from '@/lib/db';
import { fail, toJson } from '@/lib/serialize';

export const dynamic = 'force-dynamic';

/** Rates are stored as Decimal fractions; the UI works in percent and bps. */
interface MandatePatch {
  hurdleRatePct?: number;
  riskAppetiteFloor?: string;
  concentrationLimitPct?: number;
  minTicketRupees?: number;
  maxTicketRupees?: number;
  availableLiquidityRupees?: number;
}

export async function GET(_req: Request, ctx: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await ctx.params;
    const provider = await prisma.capitalProvider.findUnique({
      where: { id },
      select: {
        id: true, name: true, archetype: true,
        costOfFunds: true, hurdleRate: true, riskAppetiteFloor: true,
        totalLiquidity: true, availableLiquidity: true,
        minTicket: true, maxTicket: true,
        minTenorDays: true, maxTenorDays: true,
        concentrationLimitPct: true, settlementDays: true, sectorFocus: true,
      },
    });
    if (!provider) return fail(`No provider ${id}`, 404);
    return Response.json(toJson(provider));
  } catch (e) {
    return fail(e instanceof Error ? e.message : 'Failed to load mandate');
  }
}

export async function PATCH(req: Request, ctx: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await ctx.params;
    const body = (await req.json()) as MandatePatch;

    const data: Record<string, unknown> = {};

    // Validated at the edge rather than trusted. These values decide what
    // capital gets deployed, and a hurdle rate of -5% or a 900% concentration
    // cap would not error anywhere downstream — it would just quietly produce
    // a provider that bids on everything.
    if (body.hurdleRatePct !== undefined) {
      if (body.hurdleRatePct < 0 || body.hurdleRatePct > 100) {
        return fail('hurdleRatePct must be between 0 and 100', 400);
      }
      data.hurdleRate = (body.hurdleRatePct / 100).toFixed(6);
    }

    if (body.concentrationLimitPct !== undefined) {
      if (body.concentrationLimitPct <= 0 || body.concentrationLimitPct > 100) {
        return fail('concentrationLimitPct must be between 0 and 100', 400);
      }
      data.concentrationLimitPct = (body.concentrationLimitPct / 100).toFixed(6);
    }

    if (body.riskAppetiteFloor !== undefined) {
      if (!/^[A-E]$/.test(body.riskAppetiteFloor)) {
        return fail('riskAppetiteFloor must be a grade A–E', 400);
      }
      data.riskAppetiteFloor = body.riskAppetiteFloor;
    }

    if (body.minTicketRupees !== undefined) data.minTicket = body.minTicketRupees.toFixed(2);
    if (body.maxTicketRupees !== undefined) data.maxTicket = body.maxTicketRupees.toFixed(2);

    if (
      body.minTicketRupees !== undefined &&
      body.maxTicketRupees !== undefined &&
      body.minTicketRupees > body.maxTicketRupees
    ) {
      // Silently accepting this produces a provider that can never bid, which
      // looks like a market with no appetite rather than a misconfiguration.
      return fail('minTicket cannot exceed maxTicket', 400);
    }

    if (body.availableLiquidityRupees !== undefined) {
      if (body.availableLiquidityRupees < 0) {
        return fail('availableLiquidity cannot be negative', 400);
      }
      data.availableLiquidity = body.availableLiquidityRupees.toFixed(2);
    }

    if (Object.keys(data).length === 0) return fail('No recognised fields to update', 400);

    const updated = await prisma.capitalProvider.update({ where: { id }, data });
    return Response.json(toJson(updated));
  } catch (e) {
    return fail(e instanceof Error ? e.message : 'Failed to update mandate');
  }
}
