import { prisma } from "@/lib/db";
import { toJson, fail } from "@/lib/serialize";

export const dynamic = "force-dynamic";

/**
 * GET /api/providers        — public view (safe to render anywhere)
 * GET /api/providers?self=<providerId> — that provider's own full mandate
 *
 * A provider's mandate is private by construction. Cost of funds, hurdle rate,
 * risk floor and concentration caps are exactly the internals the scoring
 * engine must not read: if provider pricing is generated by the same logic
 * that later scores it, the market is theatre and any matching result is
 * circular (docs/01-commerce-analysis.md §6). They are also what a rival would
 * need to undercut a bid precisely.
 *
 * So the default projection omits them, and the full mandate is returned only
 * for the provider asking about itself. `self` is an identity stand-in for the
 * MVP — Sprint 2 replaces it with the session's org claim.
 */
const PUBLIC_FIELDS = {
  id: true,
  name: true,
  archetype: true,
  settlementDays: true,
  minTicket: true,
  maxTicket: true,
  minTenorDays: true,
  maxTenorDays: true,
  sectorFocus: true,
  reliabilityScore: true,
} as const;

export async function GET(request: Request) {
  try {
    const self = new URL(request.url).searchParams.get("self");

    if (self) {
      const provider = await prisma.capitalProvider.findUnique({
        where: { id: self },
        include: {
          bids: { include: { opportunity: { select: { id: true, status: true, requestedAmount: true } } } },
          escrowLocks: { where: { status: "HELD" } },
        },
      });
      if (!provider) return fail(`No provider ${self}`, 404);
      return Response.json(toJson(provider));
    }

    const providers = await prisma.capitalProvider.findMany({
      select: PUBLIC_FIELDS,
      orderBy: { name: "asc" },
    });
    return Response.json({ count: providers.length, providers: toJson(providers) });
  } catch (e) {
    return fail(e instanceof Error ? e.message : "Failed to load providers");
  }
}
